### ISSUE TITLE
Remix into Open IoT Studio!

### ISSUE THREAD

**Issue by gvn** [mozilla/openiotstudio#1]
This is just a copy of WWL right now. It'll need new content and some light design work to turn it into the Open IoT Studio's new hub.

CC: @thornet @flukeout

**Comment by gvn** [comment]
Note that deployment isn't set up yet. For reviewing the build-in-progress I'd recommend just staging on your own fork, like this: https://github.com/mozilla/openiotstudio#staging

**Comment by hannahkane** [comment]
Hey @gvn @flukeout @thornet - would it be useful for all of us to have a kickoff meeting to discuss this? I'll send calendar invites.

**Comment by gvn** [comment]
@flukeout 🤔
